import { summarize } from '../../application/dashboard/summary.js';
import { selectRequests } from '../../application/requests/service.js';
import { Icon, PageTitle, Badge } from '../components/ui.jsx';
import { numberText, dateText } from '../format.js';
import RequestTable from '../components/RequestTable.jsx';
const colors = ['#2463eb', '#f27985', '#32ba9e', '#9a7aea', '#f3b94b'];
export default function Dashboard({ records, user }) {
  const data = summarize(records);
  const cards = [ ['Toplam Talep', data.total, '', 'file', 'blue', 'Kurum genelindeki kayıtlar'], ['Açık Talepler', data.open, 'open', 'briefcase', 'green', 'Süreci devam eden'], ['Geciken Talepler', data.overdue, 'overdue', 'clock', 'red', 'Son tarihi geçen açık talepler'], ['Tamamlanan Talepler', data.completed, 'completed', 'check', 'purple', 'Tamamlandı ve kapatıldı'], ['Kritik Talepler', data.critical, 'critical', 'alert', 'orange', 'Kritik öncelikli kayıtlar'] ];
  const max = Math.max(1, ...data.trend.map(t => Math.max(t.created, t.completed)));
  const point = (n, i) => `${45 + i * 84},${164 - n / max * 128}`;
  const gradient = data.distribution.map((d, i) => { const start = data.distribution.slice(0, i).reduce((sum, item) => sum + item.count, 0) / (data.total || 1) * 100; return `${colors[i]} ${start}% ${start + d.count / (data.total || 1) * 100}%`; }).join(',');
  return <>
    <PageTitle title={`İyi çalışmalar, ${user.name}`} description="Kurum genelindeki talepleri ve öncelikli işleri tek bir yerden takip edin."><div className="today"><Icon name="calendar"/><span>{new Date().toLocaleDateString('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' })}<small>{new Date().toLocaleDateString('tr-TR', { weekday: 'long' })}</small></span></div></PageTitle>
    <div className="stats-grid">{cards.map(([label, value, quick, icon, color, hint]) => <a href={`#/requests${quick ? '?quick=' + quick : ''}`} className="stat-card" key={label}><span className={`stat-icon ${color}`}><Icon name={icon} size={23}/></span><div><span className="stat-label">{label}</span><strong>{numberText(value)}</strong><small>{hint}</small></div><Icon name="chevron" size={15}/></a>)}</div>
    <div className="dashboard-charts">
      <section className="card"><div className="card-header"><h2>Talep Trendi</h2><span className="subtle-chip">Son 6 ay</span></div><div className="chart-legend"><span><i style={{ background: colors[0] }}/>Oluşturulan</span><span><i style={{ background: colors[2] }}/>Tamamlanan</span></div><svg className="trend-chart" viewBox="0 0 510 205" role="img" aria-label={data.trend.map(t => `${t.month}: ${t.created} oluşturulan, ${t.completed} tamamlanan`).join('; ')}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2463eb" stopOpacity=".18"/><stop offset="100%" stopColor="#2463eb" stopOpacity=".01"/></linearGradient></defs>{[0, 1, 2, 3, 4].map(i => <g key={i}><line x1="40" x2="475" y1={164 - i * 32} y2={164 - i * 32} stroke="#edf0f6"/><text x="25" y={168 - i * 32} textAnchor="end">{Math.round(max * i / 4)}</text></g>)}<polygon points={`45,164 ${data.trend.map((t, i) => point(t.created, i)).join(' ')} 465,164`} fill="url(#area)"/>{['created', 'completed'].map((key, idx) => <g key={key}><polyline points={data.trend.map((t, i) => point(t[key], i)).join(' ')} fill="none" stroke={colors[idx === 0 ? 0 : 2]} strokeWidth="2.5"/>{data.trend.map((t, i) => <circle key={i} cx={45 + i * 84} cy={164 - t[key] / max * 128} r="4" fill={colors[idx === 0 ? 0 : 2]} stroke="white" strokeWidth="2"/>)}</g>)}{data.trend.map((t, i) => <text key={i} x={45 + i * 84} y="192" textAnchor="middle">{t.month}</text>)}</svg><p className="chart-footnote">Örnek kayıtların oluşturulma ve tamamlanma tarihleri</p></section>
      <section className="card"><div className="card-header"><h2>Talep Dağılımı</h2><span className="muted">Türe göre</span></div><div className="distribution"><div className="donut" style={{ background: `conic-gradient(${gradient})` }}><div><strong>{data.total}</strong><span>Toplam talep</span></div></div><div className="distribution-legend">{data.distribution.map((d, i) => <a key={d.name} href={`#/requests?type=${encodeURIComponent(d.name)}`}><i style={{ background: colors[i] }}/><span>{d.name}</span><strong>{d.count}</strong><small>%{Math.round(d.count / (data.total || 1) * 100)}</small></a>)}</div></div></section>
      <section className="card approval-card"><div className="card-header"><h2><Icon name="check"/> Onay Bekleyenler</h2><span className="badge purple">{data.approvals.length}</span></div><p className="section-description">Değerlendirmenizi bekleyen kayıtlar</p><div className="approval-list">{data.approvals.slice(0, 3).map(r => <a href={`#/requests/${r.id}`} key={r.id}><span className="approval-icon"><Icon name="file"/></span><div><strong>{r.subject}</strong><small>{r.department} · {dateText(r.createdAt)}</small></div><Icon name="chevron" size={15}/></a>)}</div>{!data.approvals.length && <p className="empty-inline">Onay bekleyen kayıt yok.</p>}<a className="card-bottom-link" href={`#/requests?status=${encodeURIComponent('Onay Bekliyor')}`}>Tüm onay bekleyenler <Icon name="arrow" size={16}/></a></section>
    </div>
    <div className="dashboard-middle"><section className="card"><div className="card-header"><h2><span className="signal red"><Icon name="alert" size={15}/></span>Acil İlgilenilmesi Gereken Talepler <span className="count-bubble">{data.urgent.length}</span></h2><a className="text-link" href="#/requests?quick=overdue">Gecikenleri gör <Icon name="arrow" size={15}/></a></div><RequestTable compact records={data.urgent.slice(0, 5)}/></section><section className="card units"><div className="card-header"><h2>Birimlere Göre Talepler</h2><Icon name="chart" size={18}/></div><div className="unit-list">{data.units.map((d, i) => <a href={`#/requests?department=${encodeURIComponent(d.name)}`} key={d.name}><div><span>{d.name}</span><strong>{d.total}</strong></div><div className="bar-track"><span style={{ width: `${d.total / Math.max(1, ...data.units.map(x => x.total)) * 100}%`, background: colors[i % 5] }}/></div><small>{d.open} açık talep</small></a>)}</div></section></div>
    <section className="card"><div className="card-header"><h2>Son Oluşturulan Talepler</h2><a className="text-link" href="#/requests">Tüm talepleri gör <Icon name="arrow" size={15}/></a></div><div className="recent-grid">{selectRequests(records).slice(0, 4).map(r => <a className="recent-item" key={r.id} href={`#/requests/${r.id}`}><div><span className="record-number">{r.number}</span><Badge>{r.status}</Badge></div><h3>{r.subject}</h3><p>{r.department}</p><small><Icon name="clock" size={13}/>{dateText(r.createdAt)}</small></a>)}</div></section>
  </>;
}
