import { useRef, useState } from 'react';
import { canAssign, departments, people, personName } from '../../domain/identity/organization.js';
import { categories, emptyDraft, localDate, priorities, privacyLevels, typeDefinitions, validateDraft } from '../../domain/requests/model.js';
import { Badge, Field, Icon, PageTitle, Select } from '../components/ui.jsx';
import { dateText } from '../format.js';
const steps = ['Temel Bilgiler', 'Detay Bilgiler', 'Ek Dosyalar', 'Kontrol Et ve Gönder'];
export default function NewRequest({ service, user, refresh, navigate }) {
  const [draft, setDraft] = useState(emptyDraft);
  const [step, setStep] = useState(0);
  const [errors, setErrors] = useState({});
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const heading = useRef(null);
  const definition = typeDefinitions.find(t => t.name === draft.type);
  const update = (key, value) => { setDraft(d => ({ ...d, [key]: value })); setErrors(e => ({ ...e, [key]: undefined })); };
  function move(next) { setStep(next); setError(''); setTimeout(() => heading.current?.focus(), 0); }
  function proceed() {
    const all = validateDraft(draft);
    const basic = ['type', 'category', 'subject', 'description', 'priority', 'department', 'dueDate', 'privacy'];
    const relevant = Object.fromEntries(Object.entries(all).filter(([key]) => step === 0 ? basic.includes(key) : step === 1 ? !basic.includes(key) : false));
    setErrors(relevant);
    if (Object.keys(relevant).length) { setError('Devam etmek için işaretli alanları kontrol edin.'); return; }
    move(step + 1);
  }
  async function submit() {
    const all = validateDraft(draft);
    if (Object.keys(all).length) { setErrors(all); setStep(0); setError('Alanları kontrol edin.'); return; }
    setBusy(true); setError('');
    try { const created = await service.create(draft); await refresh(); navigate(`/requests/${created.id}?created=1`); } catch (e) { setError(e.message); if (e.errors) setErrors(e.errors); } finally { setBusy(false); }
  }
  const userOptions = people.map(p => ({ value: p.id, label: p.name }));
  return <><a className="breadcrumb" href="#/requests">Talepler <Icon name="chevron" size={14}/>Yeni Talep</a><PageTitle title="Yeni Talep Oluştur" description="Talebinizi iletin, sürecini birlikte takip edelim."/>
    <div className="new-layout"><div><ol className="stepper">{steps.map((name, i) => <li key={name} className={i === step ? 'current' : i < step ? 'done' : ''}><span>{i < step ? <Icon name="check" size={18}/> : i + 1}</span><strong>{name}</strong></li>)}</ol><section className="card padded form-card"><h2 ref={heading} tabIndex={-1}>{step + 1}. {steps[step]}</h2><p className="section-description">{['Talebinize ait genel bilgileri girin.', 'Talep türüne özel ayrıntıları tamamlayın.', 'Talebinizi destekleyen dosyaları seçin.', 'Göndermeden önce bilgilerinizi kontrol edin.'][step]}</p>{error && <div className="error-banner" role="alert">{error}</div>}
    {step === 0 && <div className="form-grid"><Field label="Talep Türü" required error={errors.type}><Select placeholder={null} options={typeDefinitions.map(t => t.name)} value={draft.type} onChange={e => update('type', e.target.value)}/><small className="field-hint">{definition.description}</small></Field><Field label="Kategori" required error={errors.category}><Select placeholder="Kategori seçiniz" options={categories} value={draft.category} onChange={e => update('category', e.target.value)} aria-invalid={!!errors.category}/></Field><Field label="Konu" required error={errors.subject}><input value={draft.subject} onChange={e => update('subject', e.target.value)} maxLength={160} placeholder="Talebiniz için kısa ve açıklayıcı bir başlık" aria-invalid={!!errors.subject}/></Field><Field label="Öncelik" required><Select placeholder={null} options={priorities} value={draft.priority} onChange={e => update('priority', e.target.value)}/></Field><Field label="Açıklama" required className="full" error={errors.description}><textarea rows={5} maxLength={2000} value={draft.description} onChange={e => update('description', e.target.value)} placeholder="İhtiyacınızı ve beklediğiniz sonucu açıklayın…" aria-invalid={!!errors.description}/><small className="char-count">{draft.description.length} / 2.000</small></Field><Field label="İlgili Birim" required error={errors.department}><Select placeholder="Birim seçiniz" options={departments} value={draft.department} onChange={e => update('department', e.target.value)} aria-invalid={!!errors.department}/></Field><Field label="İlgili Kişi"><Select placeholder="Kişi seçiniz (isteğe bağlı)" options={userOptions} value={draft.relatedPerson} onChange={e => update('relatedPerson', e.target.value)}/></Field>{canAssign(user) && <Field label="Sorumlu" error={errors.assignee}><Select placeholder="Henüz atanmadı" options={userOptions} value={draft.assignee} onChange={e => update('assignee', e.target.value)}/><small className="muted">Genel Müdür demo rolü ile atama yapabilirsiniz.</small></Field>}<Field label="Son Tarih" required error={errors.dueDate}><input type="date" min={localDate()} value={draft.dueDate} onChange={e => update('dueDate', e.target.value)} aria-invalid={!!errors.dueDate}/></Field><Field label="Gizlilik Seviyesi" required><Select placeholder={null} options={privacyLevels} value={draft.privacy} onChange={e => update('privacy', e.target.value)}/></Field><Field label="Etiketler"><input value={draft.tags} onChange={e => update('tags', e.target.value)} placeholder="Örn. Donanım, Bilgisayar" maxLength={250}/><small className="muted">Etiketleri virgül ile ayırın.</small></Field></div>}
    {step === 1 && <div className="form-grid">{definition.fields.length ? definition.fields.map(field => <Field key={field.key} label={field.label} required={field.required} error={errors[field.key]} className={field.type === 'textarea' ? 'full' : ''}>{field.type === 'select' ? <Select placeholder="Seçiniz" options={field.options} value={draft.dynamic[field.key] || ''} onChange={e => update('dynamic', { ...draft.dynamic, [field.key]: e.target.value })}/> : field.type === 'textarea' ? <textarea rows={4} maxLength={2000} value={draft.dynamic[field.key] || ''} onChange={e => update('dynamic', { ...draft.dynamic, [field.key]: e.target.value })} aria-invalid={!!errors[field.key]}/> : <input type={field.type} min={field.min} max={field.dateRule === 'past' ? localDate() : field.max} value={draft.dynamic[field.key] || ''} onChange={e => update('dynamic', { ...draft.dynamic, [field.key]: e.target.value })} aria-invalid={!!errors[field.key]}/>}</Field>) : <div className="notice full"><Icon name="info"/>Bu talep türü için ek zorunlu alan bulunmuyor. Dosya adımına geçebilirsiniz.</div>}</div>}
    {step === 2 && <><label className="upload-area"><Icon name="upload" size={35}/><strong>Dosya seçmek için tıklayın</strong><span>Birden fazla dosya seçebilirsiniz.</span><input type="file" multiple onChange={e => { const files = Array.from(e.target.files || []).map(f => ({ name: f.name, size: f.size })); update('attachments', [...draft.attachments, ...files]); e.target.value = ''; }}/></label><div className="notice"><Icon name="info"/>Dosyalar sunucuya yüklenmez. Bu prototipte yalnızca ad ve boyut bilgisi kaydedilir.</div>{draft.attachments.map((file, i) => <div className="attachment" key={i}><Icon name="file"/><div><strong>{file.name}</strong><small>{(file.size / 1024).toLocaleString('tr-TR', { maximumFractionDigits: 1 })} KB</small></div><button className="icon-button" aria-label={`${file.name} dosyasını kaldır`} onClick={() => update('attachments', draft.attachments.filter((_, index) => i !== index))}><Icon name="close" size={17}/></button></div>)}</>}
    {step === 3 && <div className="review"><div className="review-title"><h3>{draft.subject}</h3><Badge>{draft.priority}</Badge></div><p className="description-text">{draft.description}</p><dl className="review-grid">{[['Tür', draft.type], ['Kategori', draft.category], ['İlgili Birim', draft.department], ['İlgili Kişi', personName(draft.relatedPerson)], ['Sorumlu', personName(draft.assignee)], ['Son Tarih', dateText(draft.dueDate)], ['Gizlilik', draft.privacy], ['Etiketler', draft.tags || '—'], ...definition.fields.map(f => [f.label, draft.dynamic[f.key]]), ['Dosyalar (yerel seçim)', draft.attachments.map(f => f.name).join(', ') || 'Dosya eklenmedi']].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="notice"><Icon name="info"/>Gönderdiğiniz talep örnek veri kaynağına eklenecektir. Sayfa yenilendiğinde bu oturumun değişiklikleri sıfırlanır.</div></div>}
    <footer className="form-footer"><div>{step > 0 ? <button onClick={() => move(step - 1)} disabled={busy}>← Geri</button> : <a className="button" href="#/requests">İptal</a>}</div><span>Adım {step + 1} / 4</span>{step < 3 ? <button className="primary" onClick={proceed}>Devam Et <Icon name="arrow" size={17}/></button> : <button className="primary" onClick={submit} disabled={busy}><Icon name="check" size={18}/>{busy ? 'Gönderiliyor…' : 'Talebi Gönder'}</button>}</footer></section></div>
    <aside className="new-aside"><section className="card padded"><div className="tip-title"><span className="stat-icon orange"><Icon name="bulb"/></span><h2>Hızlı Bilgi</h2></div><p className="tip-copy">Doğru talep türünü seçmek, ihtiyacınızın daha kolay anlaşılmasını sağlar.</p></section><section className="card"><div className="card-header"><h2>Talep Türleri</h2><span className="muted">{typeDefinitions.length} tür</span></div><div className="type-list">{typeDefinitions.map((t, i) => <button key={t.name} disabled={step !== 0} onClick={() => update('type', t.name)} className={draft.type === t.name ? 'selected' : ''} aria-pressed={draft.type === t.name}><span className={`stat-icon ${['blue', 'red', 'green', 'purple', 'orange'][i]}`}><Icon name={t.icon}/></span><span><strong>{t.name}</strong><small>{t.description}</small></span><span className="radio-indicator"/></button>)}</div></section><section className="card padded"><h2><Icon name="lock" size={18}/>Gizlilik ve Takip</h2><p className="section-description">Gizlilik seçimi kayıt üzerinde saklanır. Gerçek erişim denetimi backend aşamasında uygulanacaktır.</p><div className="notice">Son tarih, talebin hedef bitiş tarihidir. Bu prototip SLA hesabı yapmaz.</div></section></aside></div></>;
}
